name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: tests
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    strategy:
      matrix:
        node-version: [latest]
    env:
      NODE_ENV: test
    steps:
    - uses: actions/checkout@v4
    - name: Use NodeJS - ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
      # download pptr, inheops
    - run: node --import ./test/setup.js --experimental-test-isolation=none --test
